name: Build Airmap Platform SDK

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: recursive  
      - name: Build Airmap Platform SDK for Android and QT 5.12.10 for x86 and armv7
        run: docker build . --file docker/android-qt --tag airmap:qt
